const pnpm = "/Users/jgt/.volta/bin/pnpm";

export default {
  verificationCommands: {
    "api-course-publish": [
      pnpm,
      "--filter",
      "@web3-university/api",
      "test",
      "--",
      "course",
    ],
    "api-typecheck": [pnpm, "--filter", "@web3-university/api", "typecheck"],
    "web-course-publish": [
      pnpm,
      "--filter",
      "@web3-university/web",
      "test",
      "--",
      "app.test.tsx",
      "api.test.ts",
    ],
    "web-typecheck": [pnpm, "--filter", "@web3-university/web", "typecheck"],
    "worker-catalog": [
      "/usr/local/bin/go",
      "-C",
      "services/worker",
      "test",
      "./internal/indexer",
      "./internal/storage",
    ],
    "worker-vet": [
      "/usr/local/bin/go",
      "-C",
      "services/worker",
      "vet",
      "./...",
    ],
    "worker-catalog-postgres": [
      "/usr/bin/env",
      "XJ_REQUIRE_POSTGRES=1",
      "/usr/local/bin/go",
      "-C",
      "services/worker",
      "test",
      "./internal/indexer",
      "./internal/storage",
      "-run",
      "Catalog",
      "-count=1",
    ],
    "contracts-course-catalog": [
      "/usr/local/bin/docker",
      "run",
      "--rm",
      "-v",
      "/Users/jgt/JGTCode/codex/project/web3-university-project:/workspace",
      "-w",
      "/workspace/packages/contracts",
      "ghcr.io/foundry-rs/foundry:v1.7.1",
      "forge",
      "test",
      "--match-contract",
      "(CourseCatalogTest|DeployLocalTest)",
      "-vvv",
    ],
    "contracts-format": [
      "/usr/local/bin/docker",
      "run",
      "--rm",
      "-v",
      "/Users/jgt/JGTCode/codex/project/web3-university-project:/workspace",
      "-w",
      "/workspace/packages/contracts",
      "ghcr.io/foundry-rs/foundry:v1.7.1",
      "forge",
      "fmt",
      "--check",
    ],
    "local-course-publication-e2e": [
      "/bin/bash",
      "infra/scripts/local-course-publication-e2e.sh",
    ],
    "repo-check": [pnpm, "check"],
    "repo-typecheck": [pnpm, "typecheck"],
  },
};
