const pnpm = "/Users/jgt/.volta/bin/pnpm";

export default {
  projectId: "web3-university-project",
  environment: "local",
  taskRegistry: {
    "T-001": { role: "ops", risk: "high" },
    "T-002": { role: "ops", risk: "critical" },
  },
  capabilityRegistry: {
    coordinator: ["artifact.write", "code.read", "code.write", "test.integration", "test.run", "test.schema", "test.unit", "tool.read"],
    luna: ["code.write", "test.unit"],
    "luna-readonly": ["code.read"],
    "terra-frontend": ["code.write", "test.integration", "test.unit"],
    "terra-backend": ["code.write", "test.integration", "test.unit"],
    "terra-testing": ["code.write", "test.integration", "test.unit"],
    "terra-ops": ["code.write", "test.integration", "test.unit"],
    sol: ["code.read", "code.write", "test.integration", "test.run", "test.unit"],
  },
  verificationCommands: {
    "api-course-publish": [pnpm, "--filter", "@web3-university/api", "test", "--", "course"],
    "api-typecheck": [pnpm, "--filter", "@web3-university/api", "typecheck"],
    "api-media-schema": [
      pnpm,
      "--filter",
      "@web3-university/api",
      "test",
      "--",
      "media-schema.spec.ts",
      "course-workflow.spec.ts",
    ],
    "api-media-upload": [
      pnpm,
      "--filter",
      "@web3-university/api",
      "test",
      "--",
      "media-upload.spec.ts",
    ],
    "api-media-processing": [
      pnpm,
      "--filter",
      "@web3-university/api",
      "test",
      "--",
      "media-processing.spec.ts",
    ],
    "api-learning": [
      pnpm,
      "--filter",
      "@web3-university/api",
      "test",
      "--",
      "learning-sessions.spec.ts",
      "learning-postgres.integration.spec.ts",
    ],
    "api-certificate-admin": [
      pnpm,
      "--filter",
      "@web3-university/api",
      "test",
      "--",
      "certificate-admin.spec.ts",
    ],
    "web-course-publish": [
      pnpm,
      "--filter",
      "@web3-university/web",
      "test",
      "--",
      "app.test.tsx",
      "api.test.ts",
    ],
    "web-typecheck": [pnpm, "--filter", "@web3-university/web", "typecheck"],
    "web-learning-content": [
      pnpm,
      "--filter",
      "@web3-university/web",
      "test",
      "--",
      "course-content",
    ],
    "web-certificate-admin": [
      pnpm,
      "--filter",
      "@web3-university/web",
      "test",
      "--",
      "certificate-jobs",
    ],
    "teacher-admin-comments-closure": [pnpm, "test"],
    "worker-catalog": [
      "/usr/local/bin/go",
      "-C",
      "services/worker",
      "test",
      "./internal/indexer",
      "./internal/storage",
    ],
    "worker-vet": ["/usr/local/bin/go", "-C", "services/worker", "vet", "./..."],
    "worker-certificate-reliability": [
      "/usr/bin/env",
      "XJ_REQUIRE_POSTGRES=1",
      "/usr/local/bin/go",
      "-C",
      "services/worker",
      "test",
      "./internal/worker",
      "./internal/storage",
      "-run",
      "Certificate|Broadcast|Retry",
      "-count=1",
    ],
    "worker-catalog-postgres": [
      "/usr/bin/env",
      "XJ_REQUIRE_POSTGRES=1",
      "/usr/local/bin/go",
      "-C",
      "services/worker",
      "test",
      "./internal/indexer",
      "./internal/storage",
      "-run",
      "Catalog",
      "-count=1",
    ],
    "contracts-course-catalog": [
      "/usr/local/bin/docker",
      "run",
      "--rm",
      "-v",
      "/Users/jgt/JGTCode/codex/project/web3-university-project:/workspace",
      "-w",
      "/workspace/packages/contracts",
      "ghcr.io/foundry-rs/foundry:v1.7.1",
      "forge",
      "test",
      "--match-contract",
      "(CourseCatalogTest|DeployLocalTest)",
      "-vvv",
    ],
    "contracts-format": [
      "/usr/local/bin/docker",
      "run",
      "--rm",
      "-v",
      "/Users/jgt/JGTCode/codex/project/web3-university-project:/workspace",
      "-w",
      "/workspace/packages/contracts",
      "ghcr.io/foundry-rs/foundry:v1.7.1",
      "forge fmt --check",
    ],
    "contracts-yd-supply": [
      "/usr/local/bin/docker",
      "run",
      "--rm",
      "-v",
      "/Users/jgt/JGTCode/codex/project/web3-university-project:/workspace",
      "-w",
      "/workspace/packages/contracts",
      "ghcr.io/foundry-rs/foundry:v1.7.1",
      "forge test -vvv",
    ],
    "contracts-sepolia-prep": [
      "/usr/local/bin/docker",
      "run",
      "--rm",
      "-v",
      "/Users/jgt/JGTCode/codex/project/web3-university-project:/workspace",
      "-w",
      "/workspace/packages/contracts",
      "ghcr.io/foundry-rs/foundry:v1.7.1",
      "forge test --match-contract DeployYDSepoliaTest -vvv",
    ],
    "contracts-yd-sepolia-postdeploy": [
      "/Users/jgt/.volta/bin/node",
      "infra/scripts/verify-yd-sepolia-deployment.mjs",
    ],
    "local-course-publication-e2e": ["/bin/bash", "infra/scripts/local-course-publication-e2e.sh"],
    "local-learning-content-e2e": ["/bin/bash", "infra/scripts/local-learning-content-e2e.sh"],
    "local-certificate-e2e": ["/bin/bash", "infra/scripts/local-certificate-e2e.sh"],
    "repo-check": [pnpm, "check"],
    "repo-typecheck": [pnpm, "typecheck"],
  },
};
