// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AssetStatus string

const (
	AssetStatusREADY      AssetStatus = "READY"
	AssetStatusPROCESSING AssetStatus = "PROCESSING"
	AssetStatusFAILED     AssetStatus = "FAILED"
)

func (e *AssetStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetStatus(s)
	case string:
		*e = AssetStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetStatus: %T", src)
	}
	return nil
}

type NullAssetStatus struct {
	AssetStatus AssetStatus
	Valid       bool // Valid is true if AssetStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssetStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetStatus), nil
}

type CertificateStatus string

const (
	CertificateStatusPENDING CertificateStatus = "PENDING"
	CertificateStatusMINTING CertificateStatus = "MINTING"
	CertificateStatusMINTED  CertificateStatus = "MINTED"
	CertificateStatusFAILED  CertificateStatus = "FAILED"
)

func (e *CertificateStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CertificateStatus(s)
	case string:
		*e = CertificateStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CertificateStatus: %T", src)
	}
	return nil
}

type NullCertificateStatus struct {
	CertificateStatus CertificateStatus
	Valid             bool // Valid is true if CertificateStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCertificateStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CertificateStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CertificateStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCertificateStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CertificateStatus), nil
}

type CourseStatus string

const (
	CourseStatusDRAFT         CourseStatus = "DRAFT"
	CourseStatusPENDINGREVIEW CourseStatus = "PENDING_REVIEW"
	CourseStatusAPPROVED      CourseStatus = "APPROVED"
	CourseStatusPUBLISHED     CourseStatus = "PUBLISHED"
	CourseStatusARCHIVED      CourseStatus = "ARCHIVED"
)

func (e *CourseStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CourseStatus(s)
	case string:
		*e = CourseStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CourseStatus: %T", src)
	}
	return nil
}

type NullCourseStatus struct {
	CourseStatus CourseStatus
	Valid        bool // Valid is true if CourseStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCourseStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CourseStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CourseStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCourseStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CourseStatus), nil
}

type OutboxStatus string

const (
	OutboxStatusPENDING    OutboxStatus = "PENDING"
	OutboxStatusPROCESSING OutboxStatus = "PROCESSING"
	OutboxStatusDELIVERED  OutboxStatus = "DELIVERED"
	OutboxStatusFAILED     OutboxStatus = "FAILED"
)

func (e *OutboxStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxStatus(s)
	case string:
		*e = OutboxStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxStatus: %T", src)
	}
	return nil
}

type NullOutboxStatus struct {
	OutboxStatus OutboxStatus
	Valid        bool // Valid is true if OutboxStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxStatus), nil
}

type TeacherApplicationStatus string

const (
	TeacherApplicationStatusPENDING  TeacherApplicationStatus = "PENDING"
	TeacherApplicationStatusAPPROVED TeacherApplicationStatus = "APPROVED"
	TeacherApplicationStatusREJECTED TeacherApplicationStatus = "REJECTED"
)

func (e *TeacherApplicationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeacherApplicationStatus(s)
	case string:
		*e = TeacherApplicationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TeacherApplicationStatus: %T", src)
	}
	return nil
}

type NullTeacherApplicationStatus struct {
	TeacherApplicationStatus TeacherApplicationStatus
	Valid                    bool // Valid is true if TeacherApplicationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeacherApplicationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TeacherApplicationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeacherApplicationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeacherApplicationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeacherApplicationStatus), nil
}

type UserRole string

const (
	UserRoleSTUDENT UserRole = "STUDENT"
	UserRoleTEACHER UserRole = "TEACHER"
	UserRoleADMIN   UserRole = "ADMIN"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type ChainCheckpoint struct {
	ID              string
	ChainId         int32
	ContractAddress string
	Stream          string
	NextBlock       int64
	BlockHash       pgtype.Text
	UpdatedAt       pgtype.Timestamp
}

type Comment struct {
	ID               string
	CourseId         string
	AuthorId         string
	ParentId         pgtype.Text
	Body             string
	DeletedAt        pgtype.Timestamp
	ModeratedBy      pgtype.Text
	ModerationReason pgtype.Text
	CreatedAt        pgtype.Timestamp
}

type Course struct {
	ID                     string
	TeacherId              string
	ChainId                pgtype.Int4
	CatalogAddress         pgtype.Text
	ChainCourseId          pgtype.Text
	PriceYD                pgtype.Numeric
	PayoutWallet           pgtype.Text
	MetadataHash           pgtype.Text
	RequestedPriceYD       pgtype.Numeric
	RequestedPayoutWallet  pgtype.Text
	SubmissionHash         pgtype.Text
	CertificateMetadataUri pgtype.Text
	ReviewedBy             pgtype.Text
	ReviewedAt             pgtype.Timestamp
	Title                  string
	Description            string
	Status                 CourseStatus
	CreatedAt              pgtype.Timestamp
	UpdatedAt              pgtype.Timestamp
}

type CourseCompletion struct {
	ID            string
	CourseId      string
	UserId        string
	BuyerWalletId string
	Status        CertificateStatus
	TxHash        pgtype.Text
	TokenId       pgtype.Text
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

type EntitlementProjection struct {
	ID            string
	ChainId       int32
	BuyerWallet   string
	ChainCourseId string
	SourceEventId string
	GrantedAt     pgtype.Timestamp
	RevokedAt     pgtype.Timestamp
}

type LearningEvent struct {
	ID             string
	UserId         string
	LessonId       string
	IdempotencyKey string
	StartMs        int32
	EndMs          int32
	CreatedAt      pgtype.Timestamp
}

type LearningSegment struct {
	ID        string
	UserId    string
	LessonId  string
	StartMs   int32
	EndMs     int32
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type Lesson struct {
	ID        string
	CourseId  string
	Title     string
	Position  int32
	Required  bool
	CreatedAt pgtype.Timestamp
}

type OutboxEvent struct {
	ID             string
	Topic          string
	DedupeKey      string
	Payload        []byte
	Status         OutboxStatus
	Attempts       int32
	AvailableAt    pgtype.Timestamp
	LeaseOwner     pgtype.Text
	LeaseExpiresAt pgtype.Timestamp
	DeliveredAt    pgtype.Timestamp
	LastError      pgtype.Text
	CompletionId   string
	CreatedAt      pgtype.Timestamp
	UpdatedAt      pgtype.Timestamp
}

type ProfileChallenge struct {
	ID        string
	UserId    string
	Nonce     string
	ExpiresAt pgtype.Timestamp
	UsedAt    pgtype.Timestamp
	CreatedAt pgtype.Timestamp
}

type PurchaseEvent struct {
	ID            string
	ChainId       int32
	TxHash        string
	LogIndex      int32
	BlockNumber   int64
	BlockHash     string
	Canonical     bool
	BuyerWallet   string
	ChainCourseId string
	ObservedAt    pgtype.Timestamp
}

type TeacherApplication struct {
	ID         string
	UserId     string
	Statement  string
	Status     TeacherApplicationStatus
	ReviewedBy pgtype.Text
	ReviewedAt pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type User struct {
	ID           string
	PrivySubject string
	DisplayName  pgtype.Text
	Role         UserRole
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type VideoAsset struct {
	ID         string
	LessonId   string
	ObjectKey  string
	DurationMs int32
	Status     AssetStatus
	CreatedAt  pgtype.Timestamp
}

type Wallet struct {
	ID         string
	UserId     string
	Address    string
	ChainId    int32
	VerifiedAt pgtype.Timestamp
	IsPrimary  bool
}
