// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: outbox.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimBroadcastJobs = `-- name: ClaimBroadcastJobs :many
WITH candidates AS (
  SELECT o.id
  FROM "OutboxEvent" AS o
  JOIN "CourseCompletion" AS completion ON completion.id = o."completionId"
  JOIN "Course" AS course ON course.id = completion."courseId"
  WHERE o.topic = 'certificate.mint'
    AND o.status = 'PROCESSING'
    AND completion.status = 'MINTING'
    AND completion."txHash" IS NOT NULL
    AND course."chainCourseId" IS NOT NULL
    AND (
      o."leaseExpiresAt" IS NULL
      OR o."leaseExpiresAt" <= $1
      OR o."leaseOwner" = $2
    )
  ORDER BY o."updatedAt"
  FOR UPDATE OF o SKIP LOCKED
  LIMIT $3
), claimed AS (
  UPDATE "OutboxEvent" AS o
  SET "leaseOwner" = $2,
      "leaseExpiresAt" = $4,
      "updatedAt" = $1
  FROM candidates
  WHERE o.id = candidates.id
  RETURNING o.id, o."completionId", o.payload, o.status, o.attempts,
            o."availableAt", o."leaseOwner", o."leaseExpiresAt"
)
SELECT claimed.id AS outbox_id,
       completion."courseId" AS course_id,
       course."chainCourseId" AS chain_course_id,
       wallet.address AS buyer_address,
       claimed.payload ->> 'tokenUri' AS token_uri,
       claimed.status::text AS outbox_status,
       claimed.attempts,
       claimed."availableAt" AS available_at,
       claimed."leaseOwner" AS lease_owner,
       claimed."leaseExpiresAt" AS lease_expires_at,
       completion."txHash" AS tx_hash
FROM claimed
JOIN "CourseCompletion" AS completion ON completion.id = claimed."completionId"
JOIN "Course" AS course ON course.id = completion."courseId"
JOIN "Wallet" AS wallet ON wallet.id = completion."buyerWalletId"
`

type ClaimBroadcastJobsParams struct {
	NowAt          pgtype.Timestamp
	WorkerID       pgtype.Text
	JobLimit       int32
	LeaseExpiresAt pgtype.Timestamp
}

type ClaimBroadcastJobsRow struct {
	OutboxID       string
	CourseID       string
	ChainCourseID  pgtype.Text
	BuyerAddress   string
	TokenUri       interface{}
	OutboxStatus   string
	Attempts       int32
	AvailableAt    pgtype.Timestamp
	LeaseOwner     pgtype.Text
	LeaseExpiresAt pgtype.Timestamp
	TxHash         pgtype.Text
}

func (q *Queries) ClaimBroadcastJobs(ctx context.Context, arg ClaimBroadcastJobsParams) ([]ClaimBroadcastJobsRow, error) {
	rows, err := q.db.Query(ctx, claimBroadcastJobs,
		arg.NowAt,
		arg.WorkerID,
		arg.JobLimit,
		arg.LeaseExpiresAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimBroadcastJobsRow{}
	for rows.Next() {
		var i ClaimBroadcastJobsRow
		if err := rows.Scan(
			&i.OutboxID,
			&i.CourseID,
			&i.ChainCourseID,
			&i.BuyerAddress,
			&i.TokenUri,
			&i.OutboxStatus,
			&i.Attempts,
			&i.AvailableAt,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.TxHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimMintJobs = `-- name: ClaimMintJobs :many
WITH candidates AS (
  SELECT o.id
  FROM "OutboxEvent" AS o
  JOIN "CourseCompletion" AS completion ON completion.id = o."completionId"
  JOIN "Course" AS course ON course.id = completion."courseId"
  WHERE o.topic = 'certificate.mint'
    AND course."chainCourseId" IS NOT NULL
    AND completion.status = 'PENDING'
    AND (
      (o.status = 'PENDING' AND o."availableAt" <= $1)
      OR (o.status = 'PROCESSING' AND o."leaseExpiresAt" <= $1)
    )
  ORDER BY o."availableAt", o."createdAt"
  FOR UPDATE OF o SKIP LOCKED
  LIMIT $2
), claimed AS (
  UPDATE "OutboxEvent" AS o
  SET status = 'PROCESSING',
      "leaseOwner" = $3,
      "leaseExpiresAt" = $4,
      "updatedAt" = $1
  FROM candidates
  WHERE o.id = candidates.id
  RETURNING o.id, o."completionId", o.payload, o.status, o.attempts,
            o."availableAt", o."leaseOwner", o."leaseExpiresAt"
)
SELECT claimed.id AS outbox_id,
       completion."courseId" AS course_id,
       course."chainCourseId" AS chain_course_id,
       wallet.address AS buyer_address,
       claimed.payload ->> 'tokenUri' AS token_uri,
       claimed.status::text AS outbox_status,
       claimed.attempts,
       claimed."availableAt" AS available_at,
       claimed."leaseOwner" AS lease_owner,
       claimed."leaseExpiresAt" AS lease_expires_at,
       completion."txHash" AS tx_hash
FROM claimed
JOIN "CourseCompletion" AS completion ON completion.id = claimed."completionId"
JOIN "Course" AS course ON course.id = completion."courseId"
JOIN "Wallet" AS wallet ON wallet.id = completion."buyerWalletId"
`

type ClaimMintJobsParams struct {
	NowAt          pgtype.Timestamp
	JobLimit       int32
	WorkerID       pgtype.Text
	LeaseExpiresAt pgtype.Timestamp
}

type ClaimMintJobsRow struct {
	OutboxID       string
	CourseID       string
	ChainCourseID  pgtype.Text
	BuyerAddress   string
	TokenUri       interface{}
	OutboxStatus   string
	Attempts       int32
	AvailableAt    pgtype.Timestamp
	LeaseOwner     pgtype.Text
	LeaseExpiresAt pgtype.Timestamp
	TxHash         pgtype.Text
}

func (q *Queries) ClaimMintJobs(ctx context.Context, arg ClaimMintJobsParams) ([]ClaimMintJobsRow, error) {
	rows, err := q.db.Query(ctx, claimMintJobs,
		arg.NowAt,
		arg.JobLimit,
		arg.WorkerID,
		arg.LeaseExpiresAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimMintJobsRow{}
	for rows.Next() {
		var i ClaimMintJobsRow
		if err := rows.Scan(
			&i.OutboxID,
			&i.CourseID,
			&i.ChainCourseID,
			&i.BuyerAddress,
			&i.TokenUri,
			&i.OutboxStatus,
			&i.Attempts,
			&i.AvailableAt,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.TxHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBroadcast = `-- name: MarkBroadcast :one
WITH held_outbox AS (
  UPDATE "OutboxEvent" AS outbox
  SET "updatedAt" = $2, "lastError" = NULL
  WHERE outbox.id = $3
    AND outbox.topic = 'certificate.mint'
    AND outbox.status = 'PROCESSING'
    AND outbox."leaseOwner" = $4
    AND outbox."leaseExpiresAt" > $2
  RETURNING "completionId"
)
UPDATE "CourseCompletion" AS completion
SET status = 'MINTING', "txHash" = $1, "updatedAt" = $2
FROM held_outbox
WHERE completion.id = held_outbox."completionId"
  AND (completion."txHash" IS NULL OR completion."txHash" = $1)
RETURNING completion.id
`

type MarkBroadcastParams struct {
	TxHash   pgtype.Text
	NowAt    pgtype.Timestamp
	OutboxID string
	WorkerID pgtype.Text
}

func (q *Queries) MarkBroadcast(ctx context.Context, arg MarkBroadcastParams) (string, error) {
	row := q.db.QueryRow(ctx, markBroadcast,
		arg.TxHash,
		arg.NowAt,
		arg.OutboxID,
		arg.WorkerID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const markConfirmed = `-- name: MarkConfirmed :one
WITH held_outbox AS (
  UPDATE "OutboxEvent" AS outbox
  SET status = 'DELIVERED',
      "deliveredAt" = $3,
      "leaseOwner" = NULL,
      "leaseExpiresAt" = NULL,
      "lastError" = NULL,
      "updatedAt" = $3
  WHERE outbox.id = $4
    AND outbox.topic = 'certificate.mint'
    AND outbox.status = 'PROCESSING'
    AND outbox."leaseOwner" = $5
    AND outbox."leaseExpiresAt" > $3
  RETURNING "completionId"
)
UPDATE "CourseCompletion" AS completion
SET status = 'MINTED',
    "tokenId" = $1,
    "txHash" = COALESCE(NULLIF($2, ''), completion."txHash"),
    "updatedAt" = $3
FROM held_outbox
WHERE completion.id = held_outbox."completionId"
  AND (completion."txHash" IS NULL OR completion."txHash" = $2 OR $2 = '')
RETURNING completion.id
`

type MarkConfirmedParams struct {
	TokenID  pgtype.Text
	TxHash   interface{}
	NowAt    pgtype.Timestamp
	OutboxID string
	WorkerID pgtype.Text
}

func (q *Queries) MarkConfirmed(ctx context.Context, arg MarkConfirmedParams) (string, error) {
	row := q.db.QueryRow(ctx, markConfirmed,
		arg.TokenID,
		arg.TxHash,
		arg.NowAt,
		arg.OutboxID,
		arg.WorkerID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const markFailed = `-- name: MarkFailed :one
WITH held_outbox AS (
  UPDATE "OutboxEvent" AS outbox
  SET status = 'FAILED',
      "leaseOwner" = NULL,
      "leaseExpiresAt" = NULL,
      "lastError" = $2,
      "updatedAt" = $1
  WHERE outbox.id = $3
    AND outbox.topic = 'certificate.mint'
    AND outbox.status = 'PROCESSING'
    AND outbox."leaseOwner" = $4
    AND outbox."leaseExpiresAt" > $1
  RETURNING "completionId"
)
UPDATE "CourseCompletion" AS completion
SET status = 'FAILED', "updatedAt" = $1
FROM held_outbox
WHERE completion.id = held_outbox."completionId"
RETURNING completion.id
`

type MarkFailedParams struct {
	NowAt        pgtype.Timestamp
	ErrorMessage pgtype.Text
	OutboxID     string
	WorkerID     pgtype.Text
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) (string, error) {
	row := q.db.QueryRow(ctx, markFailed,
		arg.NowAt,
		arg.ErrorMessage,
		arg.OutboxID,
		arg.WorkerID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const scheduleRetry = `-- name: ScheduleRetry :one
WITH held_outbox AS (
  UPDATE "OutboxEvent" AS outbox
  SET status = 'PENDING',
      attempts = $2,
      "availableAt" = $3,
      "leaseOwner" = NULL,
      "leaseExpiresAt" = NULL,
      "lastError" = $4,
      "updatedAt" = $1
  WHERE outbox.id = $5
    AND outbox.topic = 'certificate.mint'
    AND outbox.status = 'PROCESSING'
    AND outbox."leaseOwner" = $6
    AND outbox."leaseExpiresAt" > $1
  RETURNING "completionId"
)
UPDATE "CourseCompletion" AS completion
SET status = CASE
      WHEN completion.status = 'MINTED' THEN 'MINTED'::"CertificateStatus"
      ELSE 'PENDING'::"CertificateStatus"
    END,
    "txHash" = CASE WHEN completion.status = 'MINTED' THEN completion."txHash" ELSE NULL END,
    "updatedAt" = $1
FROM held_outbox
WHERE completion.id = held_outbox."completionId"
RETURNING completion.id
`

type ScheduleRetryParams struct {
	NowAt         pgtype.Timestamp
	AttemptCount  int32
	NextAttemptAt pgtype.Timestamp
	ErrorMessage  pgtype.Text
	OutboxID      string
	WorkerID      pgtype.Text
}

func (q *Queries) ScheduleRetry(ctx context.Context, arg ScheduleRetryParams) (string, error) {
	row := q.db.QueryRow(ctx, scheduleRetry,
		arg.NowAt,
		arg.AttemptCount,
		arg.NextAttemptAt,
		arg.ErrorMessage,
		arg.OutboxID,
		arg.WorkerID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
