// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: purchase_index.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findApprovedCourseBySubmissionHash = `-- name: FindApprovedCourseBySubmissionHash :one
SELECT id FROM "Course"
WHERE status = 'APPROVED' AND "submissionHash" = $1
`

func (q *Queries) FindApprovedCourseBySubmissionHash(ctx context.Context, submissionHash pgtype.Text) (string, error) {
	row := q.db.QueryRow(ctx, findApprovedCourseBySubmissionHash, submissionHash)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getCheckpoint = `-- name: GetCheckpoint :one
SELECT "nextBlock", "blockHash"
FROM "ChainCheckpoint"
WHERE "chainId" = $1
  AND "contractAddress" = $2
  AND stream = $3
`

type GetCheckpointParams struct {
	ChainID         int32
	ContractAddress string
	StreamName      string
}

type GetCheckpointRow struct {
	NextBlock int64
	BlockHash pgtype.Text
}

func (q *Queries) GetCheckpoint(ctx context.Context, arg GetCheckpointParams) (GetCheckpointRow, error) {
	row := q.db.QueryRow(ctx, getCheckpoint, arg.ChainID, arg.ContractAddress, arg.StreamName)
	var i GetCheckpointRow
	err := row.Scan(&i.NextBlock, &i.BlockHash)
	return i, err
}

const projectCatalogStatus = `-- name: ProjectCatalogStatus :one
UPDATE "Course"
SET status = $1::"CourseStatus", "updatedAt" = $2
WHERE "chainId" = $3
  AND "catalogAddress" = $4
  AND "chainCourseId" = $5
  AND status IN ('PUBLISHED', 'ARCHIVED')
RETURNING id
`

type ProjectCatalogStatusParams struct {
	CourseStatus   CourseStatus
	NowAt          pgtype.Timestamp
	ChainID        pgtype.Int4
	CatalogAddress pgtype.Text
	ChainCourseID  pgtype.Text
}

func (q *Queries) ProjectCatalogStatus(ctx context.Context, arg ProjectCatalogStatusParams) (string, error) {
	row := q.db.QueryRow(ctx, projectCatalogStatus,
		arg.CourseStatus,
		arg.NowAt,
		arg.ChainID,
		arg.CatalogAddress,
		arg.ChainCourseID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const publishApprovedCourseFromCatalog = `-- name: PublishApprovedCourseFromCatalog :one
UPDATE "Course"
SET "chainId" = $1,
    "catalogAddress" = $2,
    "chainCourseId" = $3,
    "priceYD" = $4,
    "payoutWallet" = $5,
    "metadataHash" = $6,
    status = 'PUBLISHED',
    "updatedAt" = $7
WHERE id = $8
  AND status = 'APPROVED'
  AND "submissionHash" = $6
  AND "requestedPriceYD" = $4
  AND LOWER("requestedPayoutWallet") = $5
RETURNING id
`

type PublishApprovedCourseFromCatalogParams struct {
	ChainID        pgtype.Int4
	CatalogAddress pgtype.Text
	ChainCourseID  pgtype.Text
	PriceYd        pgtype.Numeric
	PayoutWallet   pgtype.Text
	MetadataHash   pgtype.Text
	NowAt          pgtype.Timestamp
	CourseID       string
}

func (q *Queries) PublishApprovedCourseFromCatalog(ctx context.Context, arg PublishApprovedCourseFromCatalogParams) (string, error) {
	row := q.db.QueryRow(ctx, publishApprovedCourseFromCatalog,
		arg.ChainID,
		arg.CatalogAddress,
		arg.ChainCourseID,
		arg.PriceYd,
		arg.PayoutWallet,
		arg.MetadataHash,
		arg.NowAt,
		arg.CourseID,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const revokeCanonicalPurchasesFrom = `-- name: RevokeCanonicalPurchasesFrom :exec
WITH reverted AS (
  UPDATE "PurchaseEvent" AS purchase
  SET canonical = false
  WHERE purchase."chainId" = $2
    AND purchase.canonical = true
    AND purchase."blockNumber" >= $3
  RETURNING purchase.id
)
UPDATE "EntitlementProjection"
SET "revokedAt" = $1
WHERE "sourceEventId" IN (SELECT id FROM reverted)
  AND "revokedAt" IS NULL
`

type RevokeCanonicalPurchasesFromParams struct {
	NowAt      pgtype.Timestamp
	ChainID    int32
	RewindFrom int64
}

func (q *Queries) RevokeCanonicalPurchasesFrom(ctx context.Context, arg RevokeCanonicalPurchasesFromParams) error {
	_, err := q.db.Exec(ctx, revokeCanonicalPurchasesFrom, arg.NowAt, arg.ChainID, arg.RewindFrom)
	return err
}

const upsertCheckpoint = `-- name: UpsertCheckpoint :exec
INSERT INTO "ChainCheckpoint" (
  id, "chainId", "contractAddress", stream, "nextBlock", "blockHash", "updatedAt"
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7
)
ON CONFLICT ("chainId", "contractAddress", stream) DO UPDATE
SET "nextBlock" = EXCLUDED."nextBlock",
    "blockHash" = EXCLUDED."blockHash",
    "updatedAt" = EXCLUDED."updatedAt"
`

type UpsertCheckpointParams struct {
	CheckpointID    string
	ChainID         int32
	ContractAddress string
	StreamName      string
	NextBlock       int64
	BlockHash       pgtype.Text
	NowAt           pgtype.Timestamp
}

func (q *Queries) UpsertCheckpoint(ctx context.Context, arg UpsertCheckpointParams) error {
	_, err := q.db.Exec(ctx, upsertCheckpoint,
		arg.CheckpointID,
		arg.ChainID,
		arg.ContractAddress,
		arg.StreamName,
		arg.NextBlock,
		arg.BlockHash,
		arg.NowAt,
	)
	return err
}

const upsertEntitlementProjection = `-- name: UpsertEntitlementProjection :exec
INSERT INTO "EntitlementProjection" (
  id, "chainId", "buyerWallet", "chainCourseId", "sourceEventId", "grantedAt", "revokedAt"
) VALUES (
  $1, $2, $3, $4,
  $5, $6, NULL
)
ON CONFLICT ("chainId", "buyerWallet", "chainCourseId") DO UPDATE
SET "sourceEventId" = EXCLUDED."sourceEventId", "grantedAt" = EXCLUDED."grantedAt", "revokedAt" = NULL
`

type UpsertEntitlementProjectionParams struct {
	ProjectionID  string
	ChainID       int32
	BuyerWallet   string
	ChainCourseID string
	SourceEventID string
	GrantedAt     pgtype.Timestamp
}

func (q *Queries) UpsertEntitlementProjection(ctx context.Context, arg UpsertEntitlementProjectionParams) error {
	_, err := q.db.Exec(ctx, upsertEntitlementProjection,
		arg.ProjectionID,
		arg.ChainID,
		arg.BuyerWallet,
		arg.ChainCourseID,
		arg.SourceEventID,
		arg.GrantedAt,
	)
	return err
}

const upsertPurchaseEvent = `-- name: UpsertPurchaseEvent :one
INSERT INTO "PurchaseEvent" (
  id, "chainId", "txHash", "logIndex", "blockNumber", "blockHash",
  canonical, "buyerWallet", "chainCourseId", "observedAt"
) VALUES (
  $1, $2, $3, $4,
  $5, $6, true, $7,
  $8, $9
)
ON CONFLICT ("chainId", "txHash", "logIndex") DO UPDATE
SET "blockNumber" = EXCLUDED."blockNumber",
    "blockHash" = EXCLUDED."blockHash",
    canonical = true,
    "buyerWallet" = EXCLUDED."buyerWallet",
    "chainCourseId" = EXCLUDED."chainCourseId",
    "observedAt" = EXCLUDED."observedAt"
RETURNING id
`

type UpsertPurchaseEventParams struct {
	EventID       string
	ChainID       int32
	TxHash        string
	LogIndex      int32
	BlockNumber   int64
	BlockHash     string
	BuyerWallet   string
	ChainCourseID string
	ObservedAt    pgtype.Timestamp
}

func (q *Queries) UpsertPurchaseEvent(ctx context.Context, arg UpsertPurchaseEventParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertPurchaseEvent,
		arg.EventID,
		arg.ChainID,
		arg.TxHash,
		arg.LogIndex,
		arg.BlockNumber,
		arg.BlockHash,
		arg.BuyerWallet,
		arg.ChainCourseID,
		arg.ObservedAt,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
